sudo: required
language: node_js
node_js:
  - "14.14.0"
services:
  - docker

before_install:
  - npm init -y
  - npm install docker-compose

before_script:
  - docker-compose -f docker-compose-dev.yml up --build --exit-code-from testweb