sudo: required
services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 3.8

before_install:
  - curl https://docs.anchore.com/current/docs/engine/quickstart/docker-compose.yaml > docker-compose.yaml

before_script:
  - docker-compose -f docker-compose-dev.yml up -d --build