sudo: required
services:
  - docker

before_install:
  - curl https://docs.anchore.com/current/docs/engine/quickstart/docker-compose.yaml > docker-compose-dev.yml

before_script:
  - docker-compose -f docker-compose-dev.yml up --build --exit-code-from testweb