sudo: required
language: node_js
node_js:
  - "14.14.0"
services:
  - docker

before_install:
  - rm -f package-lock.json && npm install --g docker-compose

before_script:
  - docker-compose -f docker-compose-dev.yml up --build --exit-code-from testweb